### ISSUE TITLE
Not working on Private repos within an organization

### ISSUE THREAD

**Issue by espoirMur** [Decathlon/release-notes-generator-action#26]
I am using this on the  to generate release not for a private repos within an organization but this cannot seems to work.

It looks like It is not able to find the issue on the repos.

Here is the errors I am getting : 

```
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) [spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:785) [spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) [spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) [spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) [spring-boot-2.4.1.jar!/:2.4.1]
	at io.spring.githubchangeloggenerator.Application.main(Application.java:33) [classes!/:0.0.6-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [github-release-notes-generator.jar:0.0.6-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) [github-release-notes-generator.jar:0.0.6-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [github-release-notes-generator.jar:0.0.6-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [github-release-notes-generator.jar:0.0.6-SNAPSHOT]
Caused by: org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found: [{"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/issues#list-repository-issues"}]
```

And you can see on this picture my token  with the credentilas : 
<img width="960" alt="Screen Shot 2021-03-04 at 17 06 06" src="https://user-images.githubusercontent.com/18573157/109984269-45428900-7d0c-11eb-91fa-16a8957af8cf.png">

and my workflow look like: 

```
on:
  milestone:
    types: [closed]
  workflow_dispatch:
    inputs:
      milestoneId:
        description: 'Milestone ID'     
        required: true
        default: '5'
name: This generate the release_notes for the milestone
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create Release Notes
      uses: docker://decathlon/release-notes-generator-action:3.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.REPOS_TOKEN }}
        OUTPUT_FOLDER: release_notes
        USE_MILESTONE_TITLE: "true"

```

**Comment by mmornati** [comment]
Thanks for your report. I made some test and found the issue related to this. Is coming in the latest versions with changes on the base spring lib. 
The name of the variables is in the following way:
```changelog:
  repository: owner/name
github:
  username:
  password:
```
and the code is providing the command line variables as `--changelog.github.username=` which is not what is expected.

There is a first workaround if you need to go on right now: you can put in the configuration file (the `release-notes.yml`) the information in the way I pasted here.
The information will be used instead of the one provided at the CLI of the action.

I'm going to make the fix in parallel.

Sorry about that.

**Comment by mmornati** [comment]
Author things, looking to your configuration. You don't need to specify a personal access token for GitHub Actions. GitHub is injecting automatically a secret with a token having access to the "current" repository.
Your secret can be:
```
env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
You can find more information here: https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret

**Comment by espoirMur** [comment]
Thanks, @mmornati  for getting back to me, I will try the workaround and get back to you with what I got.

Otherwise keep up the good work...

**Comment by espoirMur** [comment]
Thanks, @mmornati, this seems to work, .. now check where the release notes files go after the action run successfully any hint?
