### ISSUE TITLE
Error ERROR 176 Application run failed

### ISSUE THREAD

**Issue by yborf** [Decathlon/release-notes-generator-action#42]
With this workflow
```
on: 
  milestone:
    types: [closed]
name: Milestone Closure
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create Release Notes
      uses: docker://decathlon/release-notes-generator-action:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FOLDER: temp_release_notes
        USE_MILESTONE_TITLE: "true"
        FILENAME_PREFIX: MilestoneReleaseNote

```

In the step
<img width="516" alt="image" src="https://github.com/Decathlon/release-notes-generator-action/assets/1277668/64be571b-0303-4397-8ccd-e0d05e597490">

this error occurs
`2023-05-14 16:58:13.346 ERROR 176 --- [           main] o.s.boot.SpringApplication               : Application run failed
`

Details:

```
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) [spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:785) [spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) [spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) [spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) [spring-boot-2.4.1.jar!/:2.4.1]
	at io.spring.githubchangeloggenerator.Application.main(Application.java:33) [classes!/:0.0.6]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [github-release-notes-generator.jar:0.0.6]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) [github-release-notes-generator.jar:0.0.6]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [github-release-notes-generator.jar:0.0.6]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [github-release-notes-generator.jar:0.0.6]
Caused by: org.springframework.web.client.HttpClientErrorException$Forbidden: 403 Forbidden: [{"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/reference/issues#list-repository-issues"}]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:109) ~[spring-web-5.3.2.jar!/:5.3.2]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:186) ~[spring-web-5.3.2.jar!/:5.3.2]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125) ~[spring-web-5.3.2.jar!/:5.3.2]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:[63](https://github.com/yborf/Documentazione2/actions/runs/4973472478/jobs/8899348116#step:4:64)) ~[spring-web-5.3.2.jar!/:5.3.2]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:818) ~[spring-web-5.3.2.jar!/:5.3.2]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:776) ~[spring-web-5.3.2.jar!/:5.3.2]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:710) ~[spring-web-5.3.2.jar!/:5.3.2]
	at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:360) ~[spring-web-5.3.2.jar!/:5.3.2]
	at io.spring.githubchangeloggenerator.github.service.GitHubService.getPage(GitHubService.java:107) ~[classes!/:0.0.6]
	at io.spring.githubchangeloggenerator.github.service.GitHubService.getAll(GitHubService.java:95) ~[classes!/:0.0.6]
	at io.spring.githubchangeloggenerator.github.service.GitHubService.getIssuesForMilestone(GitHubService.java:90) ~[classes!/:0.0.6]
	at io.spring.githubchangeloggenerator.ChangelogGenerator.getIssues(ChangelogGenerator.java:108) ~[classes!/:0.0.6]
	at io.spring.githubchangeloggenerator.ChangelogGenerator.generate(ChangelogGenerator.java:102) ~[classes!/:0.0.6]
	at io.spring.githubchangeloggenerator.CommandProcessor.run(CommandProcessor.java:56) ~[classes!/:0.0.6]
	at io.spring.githubchangeloggenerator.CommandProcessor.run(CommandProcessor.java:[50](https://github.com/yborf/Documentazione2/actions/runs/4973472478/jobs/8899348116#step:4:51)) ~[classes!/:0.0.6]
	at io.spring.githubchangeloggenerator.CommandProcessor.run(CommandProcessor.java:44) ~[classes!/:0.0.6]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) [spring-boot-2.4.1.jar!/:2.4.1]
	... 13 common frames omitted
```

**Comment by mmornati** [comment]
Not able to see what the problem could be... but it is related to the configuration and the folder rights.
I just tried to execute the configuration [within this repository](https://github.com/Decathlon/release-notes-generator-action/blob/8135ff66479cf93e8dd8bbdf301542740539fc8d/.github/workflows/milestone.yml#LL6C1-L6C1) and the action seems to generate the release notes:
https://github.com/Decathlon/release-notes-generator-action/actions/runs/4977440894/jobs/8906514765

**Comment by mmornati** [comment]
Yes exactly... you can check with a "ls -l {folder}" inside your action.
<img width="659" alt="image" src="https://github.com/Decathlon/release-notes-generator-action/assets/139323/b52f6d7e-4d30-4c4c-bb7f-7277077b069f">
